# See keys at: https://dioxuslabs.com/learn/0.6/CLI/configure#

[application]

# App (Project) Name
name = "firefox-session-ui"

# Dioxus App Default Platform
# desktop, web, mobile, ssr
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (public) file folder
asset_dir = "public"

[web.app]

# HTML title tag content
title = "Firefox Session Data Utility"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public", "Cargo.toml", "Dioxus.toml", "src-tauri/host_commands"]

# Include style or script assets
[web.resource]

# CSS style file
style = []

# Javascript code file
script = []

[web.resource.dev]
# Same as [web.resource], but for development servers
# CSS style file
style = []

# JavaScript files
script = []
